### ISSUE TITLE
Can't Install Using Your Efi

### ISSUE THREAD

**Issue by ommi60** [chilledHamza/Hackintosh_Legion_Y7000_2018#10]
having this issue where when i click on reinstall macOs Big Sur from the usb installer, it says no internet connection, I can't even connect to internet through Lan cable, How to install please help

**Comment by chilledHamza** [comment]
Depending on your Wi-Fi adapter/chipset, try relevant driver/kernel-extension.

As for LAN controller, try [Rehabman's RealtekRTL8111](https://bitbucket.org/RehabMan/os-x-realtek-network/downloads/)

*edit: or better try offline installer prepared with "createinstallmedia"

**Comment by ommi60** [comment]
Just replaced the Rtl8111 kext with the updated version, it worked, Installing now, will let you know if any issue is found

**Comment by ommi60** [comment]
Successfully Installed, Everything is working fine but wifi and bluetooth won't work, even not showing in system prefs, what's the issue. 

![image](https://user-images.githubusercontent.com/76480042/197166358-126f3873-dd24-4a91-9fa4-fbc899adef00.jpeg)

*edit

where can i find bcm94352z adapter? when i go to the market they ask for which laptop, they don't know the models. pls help

**Comment by chilledHamza** [comment]
> where can i find bcm94352z adapter? when i go to the market they ask for which laptop, they don't know the models. pls help

Finding online is easier but little expensive.
"BCM94352Z FRU:04X6020" that i used comes with Lenovo Yoga 3
XPS 13 9343 have DW-1560 (BCM94352Z), I'm currently using this one in XPS 13 9360.
XPS 15 9550 have DW-1830 (BCM943602BAED), i had Bluetooth issues on this chipset.

There is also DW-1820A which needs different patch, might be useful if you can find one but i haven't used that personally.

Using Apple module is also possible but will require extra adapter and antenna extensions, but this is overall better as you will have working AirDrop (sending and receiving). because any of the above cannot send files with AirDrop on macOS Monterey or newer (Big Sur or older is fine), check #4 and #6 for details on Bluetooth issues with Monterey.

*edit: Forgot to mention cheaper Intel option if you need basic wireless connectivity. you might already have an intel chipset but finding one is not that hard as well. Can Simply use [AirPortItlwm](https://github.com/OpenIntelWireless/itlwm) to get any intel wireless adapter working, check #9 for details.
